### ISSUE TITLE
Where are exercises?

### ISSUE THREAD

**Issue by danbst** [python-sneks/pages#3]
Haven't found the exercises in this repo, only slides.

**Comment by acbart** [comment]
Are you looking for this? https://github.com/acbart/python-sneks

This repo is the current version of the slides. That repo had the V1 release of all the materials.

**Comment by danbst** [comment]
Ok, thanks, for some reason I've assumed this is a new version of that course.

**Comment by acbart** [comment]
It's part of the next version, but we're still testing and developing things. Hopefully we can get a V3 release some time in the next year. The curriculum has undergone a lot of changes over time based on data and experiences.
